```{r}
library(tidyverse)
library(readxl)
library(readr)
library(gptr)
library(httr2)
library(jsonlite)
library(dplyr)
library(writexl)

source('R/gpt_functions.R')
source('R/new_mvp_functions.R')
source('R/render.R')

#Rscript -e 'rmarkdown::render("cv.rmd", output_format = "pagedown::html_resume")'
```

```{r}
# 2. Load the other sheets from your original file
source_file <- "data/cv_new_reworked.xlsx"  # <- your existing file

language_skills <- read_excel(source_file, sheet = "language_skills")
text_blocks     <- read_excel(source_file, sheet = "text_blocks")
contact_info    <- read_excel(source_file, sheet = "contact_info")
```

```{r}
entries <- generate_cv_entries(
  workbook_path = "data/cv_main.xlsx",
  variant = "balanced",
  max_bullets = 3
)

entries <- entries |> 
  mutate(loc=institution) |> 
  mutate(institution=NA)
```

```{r}
entries
```


```{r}
cv_render <- list(
  entries = entries,
  language_skills = language_skills,
  text_blocks = text_blocks,
  contact_info = contact_info
)

# 4. Save to Excel
write_xlsx(cv_render, "data/cv_render_new.xlsx")
```


The code below allows to save the file to drive and already get a public url
```{r}
library(googledrive)

drive_auth()

folder <- drive_get("llm_dump")

file <- drive_upload(
  media = "data/cv_render_new.xlsx",
  path = folder,
  name = "dead_render_public4.xlsx",
  type = 'spreadsheet'
)

# Make it public (anyone with link can view)
drive_share(file, role = "reader", type = "anyone")

# Get link
file <- drive_get(as_id(file$id))  # refresh metadata

link <- file$drive_resource[[1]]$webViewLink

link
```


```{r}
link
```

Everything working, just need to add the education and stack to the pipeline. Currently manually adding, it is needed otherwise the knit breaks.

```{r}
render_cv_from_sheet(
  data_location = "https://docs.google.com/spreadsheets/d/15z7COj-Z4TDc6B4OeAID4vrMwEwLMZZhFmKyfGgrE18/edit?usp=drivesdk",
  input_file = "cv.rmd",
  output_file = "cv_au.html",
  pdf_mode = TRUE
)
```


```{r}
# Rscript -e 'rmarkdown::render("cv.rmd", output_format = "pagedown::html_resume")'
```