---
title: "Lucas Moraes's CV"
author: Lucas Moraes
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
  data_location:
    value: ""
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe

cat("CHUNK WD:", getwd(), "\n")
cat("Exists R/...", file.exists("R/cv_printing_functions.r"), "\n")
cat("Exists ../R/...", file.exists("../R/cv_printing_functions.r"), "\n")

source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = params$data_location,
  pdf_mode = params$pdf_mode,
  skip_rows = 0
)
```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Main
================================================================================

Lucas Moraes {#title}
--------------------------------------------------------------------------------

<p align="justify">
```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```
</p>

<br>

Relevant professional experience {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
**Contact**

<i class="fa fa-home"></i> [lucasmoraes.io](https://lucasmoraes.io)

<i class="fa fa-envelope"></i> moraessaur@gmail.com

<i class="fa fa-github"></i> [GitHub: `@`moraessaur](https://github.com/moraessaur)

<i class="fab fa-linkedin-in"></i> [LinkedIn](https://www.linkedin.com/in/lucas-moraes-msc-78944a32/)

:::



```{r}
CV %<>% print_section('recent_professional_experience')
```
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

::: aside
```{r,eval=FALSE}
# Tirei isso aqui com eval, eh a intro secundaria na barra lateral
CV %<>% print_text_block('recent_professional_experience_aside')
```


**Technical stack**
**__________________**

<i class="fa-solid fa-code-merge"></i> **Git**

<i class="fab fa-r-project"></i> **R**

<i class="fab fa-python"></i> **Python**

<i class="fa fa-database"></i> **SQL**

<i class="fa-solid fa-star"></i> **Spark**

<i class="fa-solid fa-circle-nodes"></i> **Data Bricks**

<i class="fas fa-chart-bar"></i> **Statistics**

<i class="fas fa-robot"></i> **Machine Learning**

<i class="fas fa-chart-area"></i> **Data Viz**

<i class="fas fa-award"></i> **Fluent english**

:::



```{r}
CV %<>% print_section('education')
```



About me {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```





